### PR TITLE
Add Performance Profiling Controller Design

### PR DESCRIPTION
**Pull request by brianrob**
Design for out-of-proc exposure of EventPipe profiling and tracing functionality.

### CODE REVIEW

**Comment by brianrob** [comment]
@Petermarcu, @valenis, @vancem, review feedback would be very much appreciated.

**Comment by SergeyKanzhelev** [comment]
CC: @nikmd23 @mmilirud @karolz-ms

@brianrob would it be more logical to offload configuration and data collection part to Application Insights SDK. ASP.NET Core 2.0 already uses Application Insights SDK as a Visual Studio debug session experience - see https://blogs.msdn.microsoft.com/webdev/2017/08/14/announcing-asp-net-core-2-0/ 

I like the idea of http-based output & configuration experience. So you can configure Application Insights SDK using this experience and get more than just http page. You'd also get channels to Elastic Search, stdout, ETW on windows.

**Comment by brianrob** [comment]
Collected feedback offline and merging.

**Comment by pharring** [comment]
I like the idea of a remote-control for profiling. But hosting an HTTP server seems (to me) like a big pill to swallow. Isn't there something lower level?

**Comment by brianrob** [comment]
@pharring, an HTTP server just just one option - I expect that we'll architect things such that other transports can be used as desired.  I would also personally like to have a way to control tracing without HTTP (something on the command line), but I'm not clear on exactly what the mechanism will be.

**Pull request merged**
