### PR TITLE
Rename OR_GREATER to OR_LATER

### PR DESCRIPTION
**Pull request by terrajobst**
Based on [feedback](https://github.com/dotnet/designs/pull/164#issuecomment-726021864)

### CODE REVIEW

**Comment by sebastienros** [comment]
Can we just count the legal votes?

**Review by akoeplinger — APPROVED** [review]

**Comment by dotMorten** [comment]
OR_GREATER makes more sense IMHO. It's a version check, not a date check

It also makes sense as part of the discussion we had about potentially having range check support in the future. Ie `#if NETVERSION>=5.0`.

**Comment by davkean** [comment]
Windows does OR_GREATER: https://docs.microsoft.com/en-us/windows/win32/sysinfo/getting-the-system-version.

**Comment by ericsampson** [comment]
Will a N-1 minor release ever happen after a N major? If so, @dotMorten has a point...

**Comment by dotMorten** [comment]
@ericsampson My understanding is it isn't the _plan_, but also never say never...

**Comment by JamesNK** [comment]
Docs tend to use "or later" when talking about version numbers:

https://www.google.com/search?q=site%3Adocs.microsoft.com+%22or+later%22

**Comment by Nirmal4G** [comment]
Can't we have both?! 😎

**Comment by Tyrrrz** [comment]
How long until full pattern matching support in compilation directives?

**Comment by Nirmal4G** [comment]
@dotMorten If you guys are sure about range check then do that instead of this.

I think having two similar things might make it worse than intented.

I vote for range check. It's simple.

**Comment by dotMorten** [comment]
@Nirmal4G range check is a _potential_ future long-term feature. Nothing for sure.

**Comment by mehrandvd** [comment]
> OR_GREATER makes more sense IMHO. It's a version check, not a date check. 5.1 could potentially be released after 6.0.
> 
> It also makes sense as part of the discussion we had about potentially having range check support in the future. Ie `#if NETVERSION>=5.0`.

What about OR_NEWER?

**Review by devlead — CHANGES_REQUESTED** [review]
Greater makes more sense IMHO, there might be things released later that aren't greater.

**Comment by umbarov** [comment]
GREATER goes well with numbers. LATER goes well with code names.
```
NET5_0_OR_GREATER
```
```
NET_PUMPKIN_OR_LATER
```

**Comment by PathogenDavid** [comment]
If we’re going to have a bikeshed party, I’d like to complicate things by proposing `_OR_NEWER`, [which is what Unity uses](https://docs.unity3d.com/Manual/PlatformDependentCompilation.html).

(I’m half joking, but I do think there’s some merit to remaining consistent with a segment of the .NET ecosystem that has actively encouraged/enabled platform-specific code through preprocessor for quite some time.)

**Comment by theo-albers** [comment]
I suggest OR_HIGHER

**Comment by alefranz** [comment]
> OR_GREATER makes more sense IMHO. It's a version check, not a date check. 5.1 could potentially be released after 6.0.
> 
Or even 3.1.11 would be a source of confusion in a month time, as released later then 5.0

**Comment by jaredpar** [comment]
Do we need to take this now `OR_LATER`?

**Comment by dotMorten** [comment]
@jaredpar I think it needs to be `AND_NEVER`

**Comment by terrajobst** [comment]
OK, considering the voting distribution I think we leave this as `OR_GREATER`.

**Pull request closed without merging**
