### PR TITLE
Preview feature: Add missing attribute targets

### PR DESCRIPTION
**Pull request by terrajobst**

### CODE REVIEW

**Review by pgovind — APPROVED** [review]
LGTM! cc @tannergooding @jeffhandley

**Comment by terrajobst** [comment]
@pgovind LOL. My goal was to bring this to API review but I guess that's good enough :-)

**Comment by terrajobst** [comment]
@dotnet/fxdc, if either of you have an issue with these changes, please speak up :-)

**Comment by bartonjs** [comment]
Retroactive LGTM :smile:

**Pull request merged**
